/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package khachsan;

import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.JOptionPane;
import java.util.*;
        

/**
 *
 * @author Pham Duc Luong
 */
public class ThayDoiQuiDinhLoaiKhach extends javax.swing.JFrame {

    /**
     * Creates new form ThayDoiQuiDinhLoaiKhach
     */
    Connect cn=null;
    String url=null;
    DefaultTableModel model=null;
    QuanLiKhachSan ql=null;
    public ThayDoiQuiDinhLoaiKhach(Connect cn1) {
        initComponents();
        this.setLocation(320, 60);
        model=(DefaultTableModel)jT_LoaiKhach.getModel();
        try{
            cn=cn1;
            ql=new QuanLiKhachSan(cn);
            ThemDuLieuVaoModel();
            
        }catch(Exception ex){
            ex.printStackTrace();
        }
        txtMaLoaiKhach.setText(MaLoaiKhach());
    }

    public void ThemDuLieuVaoModel(){
        try{
            url="SELECT*FROM LOAIKHACH " ;
            ResultSet rs=cn.ExcuteQuery(url);
            while(rs.next()){
                model.addRow(new Object[]{rs.getString(1),rs.getString(2)});
            }
            
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }
    public void XoaModel(){
        model = (DefaultTableModel) jT_LoaiKhach.getModel();
        int b = model.getRowCount();
        for (int i = 0; i < b; i++) {
            model.removeRow(0);
        }
    }
    public Boolean Kiemtratrong(){
        if(txtMaLoaiKhach.getText().length()==0||txtTenLoaiKhach.getText().length()==0){
            JOptionPane.showMessageDialog(null, "Chưa nhập đầy đủ thông tin");
            return false;
        }
        return true;
    }
    public String PhatSinhMaLoaiKhach(List<String> dsp){
        Boolean check=false;
        int a=0;
        String maloaikhach="LK";
        String mlkphatsinh=null;
        int j=1;
        if(dsp.size()==0){
            return "LK1";
        }
        while(check==false){
            a=0;
            for(int i=0;i<dsp.size();i++){
                mlkphatsinh=maloaikhach+""+j;
                if(dsp.get(i).equals(mlkphatsinh)){
                    break;
                }
                else
                    a++;
            }
            j++;
            if(a==dsp.size())
                check=true;
        }
        return mlkphatsinh;
    }
    
    public String MaLoaiKhach(){
        String url="SELECT MaLoaiKhach FROM LOAIKHACH";
        List<String> dsp=new ArrayList<>();
        try{
    
            ResultSet rs=cn.ExcuteQuery(url);
            while(rs.next()){
                dsp.add(rs.getString(1));  
            }        
        }
        catch(Exception ex){
            ex.printStackTrace();
        }

        return PhatSinhMaLoaiKhach(dsp);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMaLoaiKhach = new javax.swing.JTextField();
        txtTenLoaiKhach = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jT_LoaiKhach = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("THAY ĐỔI QUI ĐỊNH LOẠI KHÁCH CỦA KHÁCH SẠN");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin Loại khách"));

        jLabel2.setText("Mã Loại Khách");

        jLabel3.setText("Tên Loại Khách");

        txtMaLoaiKhach.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMaLoaiKhach, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenLoaiKhach, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMaLoaiKhach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTenLoaiKhach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách Loại khách"));

        jT_LoaiKhach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Loại Khách", "Tên Loại Khách"
            }
        ));
        jScrollPane1.setViewportView(jT_LoaiKhach);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton5.setText("Thoát");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Chức năng"));

        jButton1.setText("Lưu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Xóa Loại Khách");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setText("Thêm Mới");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton3.setText("Chỉnh Sửa Loại Khách");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 32, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(44, 44, 44))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (Kiemtratrong() == true) {
            url = String.format("INSERT INTO LOAIKHACH VALUES('%s','%s')", txtMaLoaiKhach.getText(), txtTenLoaiKhach.getText());
            try {
                cn.ExcuteUpdate(url);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Nhập trùng Mã Loại Khách");
            }
            model = (DefaultTableModel) jT_LoaiKhach.getModel();
            XoaModel();
            ThemDuLieuVaoModel();
            this.jButton4ActionPerformed(evt);

        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        txtMaLoaiKhach.setText(MaLoaiKhach());
        txtTenLoaiKhach.setText(null);
    }//GEN-LAST:event_jButton4ActionPerformed
    public Boolean XoaNhungThongTinLienQuan(String a,List<String> b){
        String chuoi1="";
        String chuoi2="";
        b.add("Không xóa được\nDo Mã Loại Khách "+a+" có trong Phiếu Thuê Phòng: ");
        try{
            String url="SELECT DISTINCT PHIEUTHUEPHONG.MaPhieuThuePhong\n" +
                        "FROM PHIEUTHUEPHONG,LOAIKHACH,CT_PHIEUTHUEPHONG\n" +
                        "WHERE LOAIKHACH.MaLoaiKhach=CT_PHIEUTHUEPHONG.MaLoaiKhach AND PHIEUTHUEPHONG.MaPhieuThuePhong=CT_PHIEUTHUEPHONG.MaPhieuThuePhong AND LOAIKHACH.MaLoaiKhach='"+a+"'";
            ResultSet rs=cn.ExcuteQuery(url);
            while(rs.next()){
                chuoi1=chuoi1+rs.getString(1)+"  ";
            }
            if(chuoi1.equals("")==false){
                b.set(0, b.get(0)+chuoi1);
            }
            url="SELECT DISTINCT CT_HOADON.MaHoaDon\n" +
                        "FROM PHIEUTHUEPHONG,CT_HOADON,LOAIKHACH,CT_PHIEUTHUEPHONG\n" +
                        "WHERE LOAIKHACH.MaLoaiKhach=CT_PHIEUTHUEPHONG.MaLoaiKhach AND PHIEUTHUEPHONG.MaPhieuThuePhong=CT_PHIEUTHUEPHONG.MaPhieuThuePhong AND PHIEUTHUEPHONG.MaPhieuThuePhong=CT_HOADON.MaPhieuThuePhong AND LOAIKHACH.MaLoaiKhach='"+a+"'";
            rs=cn.ExcuteQuery(url);
            while(rs.next()){
                chuoi2=chuoi2+rs.getString(1)+"  ";
            }
            if(chuoi2.equals("")==false){
                    b.set(0, b.get(0)+"\nVà có trong Hóa Đơn: "+chuoi2);
            }
        }catch(Exception ex){
            ex.printStackTrace();
        }
        if(chuoi1.equals("")==false||chuoi2.equals("")==false)
            return false;
        return true;
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int[] index = jT_LoaiKhach.getSelectedRows();
        if(index.length==0){
            JOptionPane.showMessageDialog(null, "Chưa chọn hàng để xóa");           
        }
        else{     
            model = (DefaultTableModel) jT_LoaiKhach.getModel();
            System.out.println(model.getRowCount());
            try {
                int dem=0;
                for (int i = 0; i < index.length; i++) {
                    List<String> b=new ArrayList<>();
                    if(XoaNhungThongTinLienQuan(model.getValueAt((index[i]-dem), 0).toString(),b)==false){
                        JOptionPane.showMessageDialog(null, b.get(0));
                    }
                    else{
                        url="DELETE FROM LOAIKHACH WHERE MaLoaiKhach='"+model.getValueAt((index[i]-dem), 0).toString()+"'";
                        cn.ExcuteUpdate(url);   
                        model.removeRow(index[i]-dem);
                        dem++;
                    }  
                }
                
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
        txtMaLoaiKhach.setText(MaLoaiKhach());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        model = (DefaultTableModel) jT_LoaiKhach.getModel();
        int index=-1;
        index = jT_LoaiKhach.getSelectedRow();
        if(index==-1){
            JOptionPane.showMessageDialog(null,"Chưa chọn hàng để chỉnh sửa");
        }
        else {
            List<String> a = new ArrayList<>();
            for (int i = 0; i < model.getColumnCount(); i++) {
                a.add(model.getValueAt(index, i).toString());
            }
            SuaLoaiKhach slk = new SuaLoaiKhach(this,cn);
            slk.Loaddulieu(a);
            slk.setVisible(true);
            this.setEnabled(false);
        }  
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int b=JOptionPane.showConfirmDialog(null, "Bạn có muốn thoát Thay Đổi Qui Định không?", "Thoat", JOptionPane.YES_OPTION);
        if(b==0){
            int c=JOptionPane.showConfirmDialog(this, "Bạn có muốn trở về Màn hình chính không", "Thoát", JOptionPane.YES_OPTION);
         if (c == 0) {
                this.setVisible(false);
                ql.setEnabled(true);
                ql.setVisible(true);
            } else {
                System.exit(0);
            }
            
        } 
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThayDoiQuiDinhLoaiKhach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThayDoiQuiDinhLoaiKhach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThayDoiQuiDinhLoaiKhach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThayDoiQuiDinhLoaiKhach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jT_LoaiKhach;
    private javax.swing.JTextField txtMaLoaiKhach;
    private javax.swing.JTextField txtTenLoaiKhach;
    // End of variables declaration//GEN-END:variables
}
